### ISSUE TITLE
[BUG] pdftocairo not executed

### ISSUE THREAD

**Issue by MaikBrant** [ahnafnafee/PostScript-Preview#12]
![image](https://github.com/user-attachments/assets/f8d38465-87b5-44a4-a085-001b736d0c8e)
Failed to execute pdftocairo. Report bug with postscript file to dev.

**Comment by ahnafnafee** [comment]
I believe you will need to install "poppler" version 0.89.0 to be able to execute pdftocairo correctly. I will update the README to address that. Please let me know if that does not solve your issue.

```powershell
choco install poppler --version 0.89.0 -y --force
```

**Comment by MaikBrant** [comment]
it worked, but nothing is displayed, just an empty page

![image](https://github.com/user-attachments/assets/cc2ece8f-e0b5-44ac-86ba-78809aae5dc4)

**Comment by ahnafnafee** [comment]
Hi @MaikBrant, could you share the postscript file or an example one that has the same issue? Thanks!

**Comment by MaikBrant** [comment]
This is my first job in this programming language, maybe I need to start the file in a special way?

**Comment by ahnafnafee** [comment]
I believe there are multiple ways to define headers for postscript file. However, it will be difficult to debug this issue without a reproducible example file.

Are you able to view the file using GhostScript?

**Comment by MaikBrant** [comment]
% Фон
newpath
0.0 0.2 0.5 setrgbcolor
0 0 moveto
612 0 lineto
612 792 lineto
0 792 lineto
closepath
fill

% Луна
1.0 1.0 0.6 setrgbcolor
300 700 70 0 360 arc
fill

 

% Земля
newpath
0.0 0.0 0.0 setrgbcolor
0 0 moveto
612 0 lineto
612 100 lineto
0 100 lineto
closepath
fill

%холм1
newpath
	0.1 0.3 0.1 setrgbcolor
	0 100 moveto
    0 250 rlineto
    170 200 rlineto
    400 -450 rlineto
    closepath
    gsave
	fill 


%холм2
newpath
	0.2 0.3 0.1 setrgbcolor
	0 100 moveto
    400 500 rlineto
    400 -500 rlineto
    closepath
    gsave
	fill 
    
    
%дом1
newpath
	10 100 moveto
    0 300 rlineto
    170 0 rlineto
    0 -300 rlineto
    closepath
    gsave
    0.5 0.5 0.5 setrgbcolor
	fill

   %кусочек дерева нижний
newpath
	0.1 0.4 0.0 setrgbcolor
	400 210 moveto
    100 100 rlineto
    100 -100 rlineto
    closepath
    gsave
	fill 
    
%кусочек дерева средний
newpath
	0.1 0.5 0.1 setrgbcolor
	400 265 moveto
    100 100 rlineto
    100 -100 rlineto
    closepath
    gsave
	fill
    
    %кусочек дерева верхний
newpath
	0.1 0.6 0.0 setrgbcolor
	400 320 moveto
    100 100 rlineto
    100 -100 rlineto
    closepath
    gsave
	fill

   %ствол
newpath
	490 100 moveto
    0 110 rlineto
    20 0 rlineto
    0 -110 rlineto
    closepath
    gsave
    0.3 0.2 0.1 setrgbcolor
	fill
    
    %окно1
newpath
	25 200 moveto
    0 60 rlineto
    60 0 rlineto
    0 -60 rlineto
    closepath
    gsave
    1.0 0.9 0.2 setrgbcolor
	fill
     
    %окно2
newpath
	105 200 moveto
    0 60 rlineto
    60 0 rlineto
    0 -60 rlineto
    closepath
    gsave
    1.0 0.9 0.2 setrgbcolor
	fill

    %окно3
newpath
	105 280 moveto
    0 60 rlineto
    60 0 rlineto
    0 -60 rlineto
    closepath
    gsave
    1.0 0.9 0.2 setrgbcolor
	fill

%окно4
newpath
	25 280 moveto
    0 60 rlineto
    60 0 rlineto
    0 -60 rlineto
    closepath
    gsave
    1.0 0.9 0.2 setrgbcolor
	fill

% дом2
newpath
180 100 moveto
0 250 rlineto
160 0 rlineto
0 -250 rlineto
closepath
   gsave
   0.3 0.3 0.3 setrgbcolor
	fill
    
    %окно1
newpath
	200 200 moveto
    0 50 rlineto
    50 0 rlineto
    0 -50 rlineto
    closepath
    gsave
    1.0 0.9 0.2 setrgbcolor
	fill

    %окно3
newpath
	265 260 moveto
    0 50 rlineto
    50 0 rlineto
    0 -50 rlineto
    closepath
    gsave
    1.0 0.9 0.2 setrgbcolor
	Fill
Here is example, when I use GhostScript image displayed, but in Visual Studio nothing is displayed

**Comment by MaikBrant** [comment]
@ahnafnafee, I'm sorry to bother you, but is there any way to solve my problem, or do I need to look for alternative ways to solve the problem?

**Comment by MaikBrant** [comment]
The problem was in the name of the folder where the file was stored
