### ISSUE TITLE
[BUG] Failed to execute pdf2svg, is that installed?

### ISSUE THREAD

**Issue by jiangyundi** [ahnafnafee/PostScript-Preview#4]
**Describe the bug**
After following the steps of installations of GS9.55.0 and pdf2svg, I can run the pdf2svg  and ps2pdf at the terminal, but if I click the button of preview Postscript then show the message' Failed to execute pdf2svg, is that installed?'

**Desktop (please complete the following information):**
 - OS: [Windows11]
 - Version [e.g. 0.3.0]

**Comment by ahnafnafee** [comment]
Hi, are you able run pdf2svg and ps2pdf in the command prompt?

**Comment by Godzilla84** [comment]
Hi, I have exactly the same issue. I can run both commands in CMD. When I try to run those commands in powershell ps2pdf is not recognized. Everything is installed with chocolately and I adde all paths manually.

**Comment by ahnafnafee** [comment]
> 
> 
> Hi, I have exactly the same issue. I can run both commands in CMD. When I try to run those commands in powershell ps2pdf is not recognized. Everything is installed with chocolately and I added all paths manually. I use Windows 10 version 21H1.

@Godzilla84 Could you try adding the paths to the system variables PATH instead?

![image](https://user-images.githubusercontent.com/48362866/141201812-eddb37fd-e770-418b-9331-e12669447004.png)

```bash
C:\Program Files\gs\gs9.55.0\lib
C:\Program Files\gs\gs9.55.0\bin
```

**Comment by Godzilla84** [comment]
Yes, i tried that. Now both commands work at Powershell but now i get "Failed to execute pdf2svg, is that installed?", weird..

**Comment by ahnafnafee** [comment]
@Godzilla84 Could you try adding the following line to the system variables as well?
```bash
C:\ProgramData\chocolatey\lib\pdf2svg\tools\pdf2svg-windows-master\dist-64bits
```
Then try running pdf2svg in Powershell

**Comment by Godzilla84** [comment]
@ahnafnafee I added that line to both user and system variables, pdf2svg and ps2pdf both work in powershell, but i still get "Failed to execute pdf2svg, is that installed?" error.

**Comment by ahnafnafee** [comment]
@Godzilla84 Could you verify if you can go to the folder: `C:\ProgramData\chocolatey\lib\pdf2svg\tools\pdf2svg-windows-master\dist-64bits` from File Explorer?

And if you can see the following files there:
![image](https://user-images.githubusercontent.com/48362866/141329089-681dbfdc-0aff-4a29-bb0c-0e80108072f8.png)

**Comment by Godzilla84** [comment]
@ahnafnafee yes, i can access that folder when i paste that in file explorer and all the files from your picture are there.

**Comment by ahnafnafee** [comment]
@Godzilla84 Could you try running this command in PowerShell (in Admin) 

```bash
[Environment]::SetEnvironmentVariable("Path",[Environment]::GetEnvironmentVariable("Path", [EnvironmentVariableTarget]::Machine) + ";C:\Program Files\gs\gs9.55.0\lib;C:\Program Files\gs\gs9.55.0\bin;C:\ProgramData\chocolatey\lib\pdf2svg\tools\pdf2svg-windows-master\dist-64bits",[EnvironmentVariableTarget]::Machine)
```
Then restart VSCode and try again

**Comment by Godzilla84** [comment]
@ahnafnafee i did that and restarted vsc and i still get that error "Failed to execute pdf2svg, is that installed?"

**Comment by ahnafnafee** [comment]
@Godzilla84 Are you also using Win 11? It might be an OS issue that I am not aware of so I'm unable to debug this at the moment unfortunately

**Comment by Godzilla84** [comment]
@ahnafnafee nope, I use Windows 10 version 21H1. Is it possible that ps files im trying to open are problem? If so, could you maybe send me small postscript code snippet that works on your pc for preview so i can try to open it?

**Comment by ahnafnafee** [comment]
@Godzilla84 You can try opening this basic PostScript file: https://github.com/ahnafnafee/PostScript-Preview/blob/master/test_eps/out.ps

Also, could you attach the postscript file you are trying to preview if possible?

**Comment by Godzilla84** [comment]
@ahnafnafee i tried opening your file and preview works. For every one of my files preview won't open.. here's one example:

`50 50 translate
/mreza {0.5 0.3 0 0 setcmykcolor 
gsave
2 setlinewidth 500 0 moveto 0 0 lineto 0 500 lineto stroke
grestore
gsave
0.3 setlinewidth
5 { 30 100 moveto 500 100 lineto stroke 0 100 translate } repeat
grestore
gsave
0.3 setlinewidth
5 { 100 20 moveto 100 500 lineto stroke 100 0 translate } repeat
grestore
gsave
/tekst 3 string def /Helvetica findfont 10 scalefont setfont
100 100 500 { /y exch def 5 y 2 sub moveto y tekst cvs show } for
90 100 500 { /x exch def x 5 moveto x 10 add tekst cvs show } for
grestore 
0 setgray } bind def
mreza

0.5 setgray
4 setlinewidth
200 300 moveto
100 100 lineto
300 100 lineto
closepath
1 setlinejoin
2 setlinecap
fill

0.9 setgray
175 250 moveto
200 300 lineto
225 250 lineto
210 230 lineto
200 250 lineto
190 235 lineto
closepath
fill

1 setgray
150 100 moveto
150 150 lineto
140 140 lineto
150 150 moveto
160 140 lineto
150 130 moveto
140 120 lineto
150 130 moveto
160 120 lineto

250 100 moveto
250 150 lineto
240 140 lineto
250 150 moveto
260 140 lineto
250 130 moveto
240 120 lineto
250 130 moveto
260 120 lineto
stroke

200 100 moveto
200 200 lineto
190 190 lineto
200 200 moveto
210 190 lineto
200 180 moveto
190 170 lineto
200 180 moveto
210 170 lineto
200 160 moveto
190 150 lineto
200 160 moveto
210 150 lineto
1 setlinecap
stroke

0 setgray
4 setlinewidth
175 250 moveto
100 100 lineto
300 100 lineto
225 250 lineto
1 setlinejoin
2 setlinecap
stroke

0.9 setgray
175 250 moveto
200 300 lineto
225 250 lineto
210 230 lineto
200 250 lineto
190 235 lineto
0 setlinejoin
0 setlinecap
stroke
fill`

**Comment by ahnafnafee** [comment]
@Godzilla84 Could you run the following in PowerShell Admin?
```bash
choco install poppler -y
[Environment]::SetEnvironmentVariable("Path",[Environment]::GetEnvironmentVariable("Path", [EnvironmentVariableTarget]::Machine) + ";C:\ProgramData\chocolatey\lib\poppler\tools",[EnvironmentVariableTarget]::Machine)
```
I pushed a new update to the extension. Try updating to that and then reload vscode. Hopefully should fix the issue.

**Comment by Godzilla84** [comment]
@Godzilla84 i did everything you said and it works now! thank you for assisting me! :)

**Comment by jiangyundi** [comment]
Thank you very much!
