### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by b-kovacs** [ahnafnafee/PostScript-Preview#8]
**Describe the bug**
The Plugin doesn't work in WSL enviroment

**To Reproduce**
Just install on the wsl side as requested by the tool

**Comment by b-kovacs** [comment]
Failed to execute pdftocairo. Report bug with postscript file to dev. That's also the message that pops up once you try to run this plugin in wsl

**Comment by ahnafnafee** [comment]
I believe you will need to install "poppler-utils" to be able to execute pdftocairo. I will update the README to address that. Please let me know if that does not solve your issue.
```bash
sudo apt-get install poppler-utils -y
```
